name: full-quality-assurance

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]
    name: Test for Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm dependencies
      run: npm ci
    - name: Build packages
      run: npm run build
    - name: Run tests
      run: npm test

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint

  license:
    name: Check license conformity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run license check
      run: npm run license

  version:
    name: Check version update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run license check
      run: npm run version

  generate-docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Build packages
      run: npm run build
    - name: Generate docs
      run: npm run docs
    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: dvelop-sdk-${{github.run_id}}-docs
        path: docs

  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: "@dvelop-sdk-${{github.run_id}}"
        path: |
          packages/*/lib/*
          packages/*/package.json
          packages/*/package-lock.json
          packages/*/README.md