on: [push]

stages:
  - quality-assurance
  - deploy

runs-on: ubuntu-latest
cache:
  key:
    files:
      - package.json
      - package-lock.json
  paths:
    - node_modules/
    - packages/*/node_modules/

test:
  stage: quality-assurance
  strategy:
    matrix:
      node-version: [10.x, 12.x, 14.x, 15.x]
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: ${{ matrix.node-version }}
      registry-url: 'https://registry.npmjs.org'
  - run: npm ci
  - run: npm test

lint:
  stage: quality-assurance
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
  - run: npm ci
  - run: npm run lint

docs:
  stage: quality-assurance
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
  - run: npm ci
  - run: npm run docs