name: release

on:
  push:
    branches:
      - master
      - develop

jobs:
  release-docs:
    name: release documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Generate docs
      run: npm run docs
    - name: Commit docs to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: docs

  publish-prerelease:
    name: Publish Prerelease to npm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Set release credentials
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Publish code
      run: lerna publish prerelease --no-push --no-verify-access --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}