name: slim-quality-assurance

on:
  pull_request:
    branches-ignore:
      - master
      - develop

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm dependencies
      run: npm ci
    - name: Build packages
      run: npm run build
    - name: Run tests
      run: npm test

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint

  license:
    name: Check license conformity
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
    - name: Install npm dependencies
      run: npm ci
    - name: Run license check
      run: npm run license
